// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: LzsCvDataProtoCs.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace LiveSplit.Lazysplits.Proto {

  /// <summary>Holder for reflection information generated from LzsCvDataProtoCs.proto</summary>
  public static partial class LzsCvDataProtoCsReflection {

    #region Descriptor
    /// <summary>File descriptor for LzsCvDataProtoCs.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static LzsCvDataProtoCsReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChZMenNDdkRhdGFQcm90b0NzLnByb3RvEhpMaXZlU3BsaXQuTGF6eXNwbGl0",
            "cy5Qcm90byIhCglVU2NhbGFyMmQSCQoBeBgBIAEoDRIJCgF5GAIgASgNIisK",
            "CFJHQkNvbG9yEgkKAVIYASABKA0SCQoBRxgCIAEoDRIJCgFCGAMgASgNInsK",
            "CEdhbWVMaXN0Ej0KBWdhbWVzGAEgAygLMi4uTGl2ZVNwbGl0LkxhenlzcGxp",
            "dHMuUHJvdG8uR2FtZUxpc3QuR2FtZUVudHJ5GjAKCUdhbWVFbnRyeRIMCgRu",
            "YW1lGAEgASgJEhUKDXJlbGF0aXZlX3BhdGgYAiABKAkijwEKCEdhbWVJbmZv",
            "EgwKBG5hbWUYASABKAkSQQoHdGFyZ2V0cxgCIAMoCzIwLkxpdmVTcGxpdC5M",
            "YXp5c3BsaXRzLlByb3RvLkdhbWVJbmZvLlRhcmdldEVudHJ5GjIKC1Rhcmdl",
            "dEVudHJ5EgwKBG5hbWUYASABKAkSFQoNcmVsYXRpdmVfcGF0aBgCIAEoCSLv",
            "AQoKVGFyZ2V0SW5mbxIMCgRuYW1lGAEgASgJEjQKBHR5cGUYAiABKA4yJi5M",
            "aXZlU3BsaXQuTGF6eXNwbGl0cy5Qcm90by5UYXJnZXRUeXBlEhcKD3NwbGl0",
            "X29mZnNldF9tcxgDIAEoERJCCgd3YXRjaGVzGAQgAygLMjEuTGl2ZVNwbGl0",
            "LkxhenlzcGxpdHMuUHJvdG8uVGFyZ2V0SW5mby5XYXRjaEVudHJ5GkAKCldh",
            "dGNoRW50cnkSDAoEbmFtZRgBIAEoCRIVCg1yZWxhdGl2ZV9wYXRoGAIgASgJ",
            "Eg0KBWluZGV4GAMgASgNIv8GCglXYXRjaEluZm8SDAoEbmFtZRgBIAEoCRIz",
            "CgR0eXBlGAIgASgOMiUuTGl2ZVNwbGl0LkxhenlzcGxpdHMuUHJvdG8uV2F0",
            "Y2hUeXBlEj4KD2Jhc2VfZGltZW5zaW9ucxgDIAEoCzIlLkxpdmVTcGxpdC5M",
            "YXp5c3BsaXRzLlByb3RvLlVTY2FsYXIyZBI9CgRhcmVhGAQgASgLMi8uTGl2",
            "ZVNwbGl0LkxhenlzcGxpdHMuUHJvdG8uV2F0Y2hJbmZvLldhdGNoQXJlYRIz",
            "CgVjb2xvchgFIAEoCzIkLkxpdmVTcGxpdC5MYXp5c3BsaXRzLlByb3RvLlJH",
            "QkNvbG9yEhkKEWltZ19yZWxhdGl2ZV9wYXRoGAYgASgJEkcKEWNoYXJhY3Rl",
            "cl9qdXN0aWZ5GAcgASgOMiwuTGl2ZVNwbGl0LkxhenlzcGxpdHMuUHJvdG8u",
            "Q2hhcmFjdGVySnVzdGlmeRJGChFjaGFyYWN0ZXJfel9vcmRlchgIIAEoDjIr",
            "LkxpdmVTcGxpdC5MYXp5c3BsaXRzLlByb3RvLkNoYXJhY3RlclpPcmRlchJI",
            "CgpjaGFyYWN0ZXJzGAkgAygLMjQuTGl2ZVNwbGl0LkxhenlzcGxpdHMuUHJv",
            "dG8uV2F0Y2hJbmZvLkNoYXJhY3RlckVudHJ5ElgKEmFkZGl0aW9uYWxfcGFk",
            "ZGluZxgKIAMoCzI8LkxpdmVTcGxpdC5MYXp5c3BsaXRzLlByb3RvLldhdGNo",
            "SW5mby5BZGRpdGlvbmFsUGFkZGluZ0VudHJ5GnQKCVdhdGNoQXJlYRIyCgNs",
            "b2MYASABKAsyJS5MaXZlU3BsaXQuTGF6eXNwbGl0cy5Qcm90by5VU2NhbGFy",
            "MmQSMwoEc2l6ZRgCIAEoCzIlLkxpdmVTcGxpdC5MYXp5c3BsaXRzLlByb3Rv",
            "LlVTY2FsYXIyZBpmCg5DaGFyYWN0ZXJFbnRyeRIXCg9jaGFyYWN0ZXJfaW5k",
            "ZXgYASABKA0SFQoNY2hhcmFjdGVyX3ZhbBgCIAEoCRIRCgl4X3BhZGRpbmcY",
            "AyABKBESEQoJeV9wYWRkaW5nGAQgASgRGk0KFkFkZGl0aW9uYWxQYWRkaW5n",
            "RW50cnkSIgoaY2hhcmFjdGVyX2xlbmd0aF90aHJlc2hvbGQYASABKA0SDwoH",
            "cGFkZGluZxgCIAEoESpZCgpUYXJnZXRUeXBlEg4KClRHVF9VTlVTRUQQABIN",
            "CglUR1RfUkVTRVQQARINCglUR1RfU1RBUlQQAhIQCgxUR1RfU1RBTkRBUkQQ",
            "AxILCgdUR1RfRU5EEAQqUwoJV2F0Y2hUeXBlEg0KCVdUX1VOVVNFRBAAEgwK",
            "CFdUX0NPTE9SEAESEwoPV1RfSU1BR0VfU1RBVElDEAISFAoQV1RfQ0hBUkFD",
            "VEVSX1NFVBADKmkKEENoYXJhY3Rlckp1c3RpZnkSHAoYQ0hBUkFDVEVSX0pV",
            "U1RJRllfVU5VU0VEEAASGgoWQ0hBUkFDVEVSX0pVU1RJRllfTEVGVBABEhsK",
            "F0NIQVJBQ1RFUl9KVVNUSUZZX1JJR0hUEAIqZwoPQ2hhcmFjdGVyWk9yZGVy",
            "EhYKEkNIQVJBQ1RFUl9aX1VOVVNFRBAAEh0KGUNIQVJBQ1RFUl9aX0xFRlRf",
            "VE9fUklHSFQQARIdChlDSEFSQUNURVJfWl9SSUdIVF9UT19MRUZUEAJiBnBy",
            "b3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::LiveSplit.Lazysplits.Proto.TargetType), typeof(global::LiveSplit.Lazysplits.Proto.WatchType), typeof(global::LiveSplit.Lazysplits.Proto.CharacterJustify), typeof(global::LiveSplit.Lazysplits.Proto.CharacterZOrder), }, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::LiveSplit.Lazysplits.Proto.UScalar2d), global::LiveSplit.Lazysplits.Proto.UScalar2d.Parser, new[]{ "X", "Y" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::LiveSplit.Lazysplits.Proto.RGBColor), global::LiveSplit.Lazysplits.Proto.RGBColor.Parser, new[]{ "R", "G", "B" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::LiveSplit.Lazysplits.Proto.GameList), global::LiveSplit.Lazysplits.Proto.GameList.Parser, new[]{ "Games" }, null, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::LiveSplit.Lazysplits.Proto.GameList.Types.GameEntry), global::LiveSplit.Lazysplits.Proto.GameList.Types.GameEntry.Parser, new[]{ "Name", "RelativePath" }, null, null, null)}),
            new pbr::GeneratedClrTypeInfo(typeof(global::LiveSplit.Lazysplits.Proto.GameInfo), global::LiveSplit.Lazysplits.Proto.GameInfo.Parser, new[]{ "Name", "Targets" }, null, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::LiveSplit.Lazysplits.Proto.GameInfo.Types.TargetEntry), global::LiveSplit.Lazysplits.Proto.GameInfo.Types.TargetEntry.Parser, new[]{ "Name", "RelativePath" }, null, null, null)}),
            new pbr::GeneratedClrTypeInfo(typeof(global::LiveSplit.Lazysplits.Proto.TargetInfo), global::LiveSplit.Lazysplits.Proto.TargetInfo.Parser, new[]{ "Name", "Type", "SplitOffsetMs", "Watches" }, null, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::LiveSplit.Lazysplits.Proto.TargetInfo.Types.WatchEntry), global::LiveSplit.Lazysplits.Proto.TargetInfo.Types.WatchEntry.Parser, new[]{ "Name", "RelativePath", "Index" }, null, null, null)}),
            new pbr::GeneratedClrTypeInfo(typeof(global::LiveSplit.Lazysplits.Proto.WatchInfo), global::LiveSplit.Lazysplits.Proto.WatchInfo.Parser, new[]{ "Name", "Type", "BaseDimensions", "Area", "Color", "ImgRelativePath", "CharacterJustify", "CharacterZOrder", "Characters", "AdditionalPadding" }, null, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::LiveSplit.Lazysplits.Proto.WatchInfo.Types.WatchArea), global::LiveSplit.Lazysplits.Proto.WatchInfo.Types.WatchArea.Parser, new[]{ "Loc", "Size" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::LiveSplit.Lazysplits.Proto.WatchInfo.Types.CharacterEntry), global::LiveSplit.Lazysplits.Proto.WatchInfo.Types.CharacterEntry.Parser, new[]{ "CharacterIndex", "CharacterVal", "XPadding", "YPadding" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::LiveSplit.Lazysplits.Proto.WatchInfo.Types.AdditionalPaddingEntry), global::LiveSplit.Lazysplits.Proto.WatchInfo.Types.AdditionalPaddingEntry.Parser, new[]{ "CharacterLengthThreshold", "Padding" }, null, null, null)})
          }));
    }
    #endregion

  }
  #region Enums
  public enum TargetType {
    [pbr::OriginalName("TGT_UNUSED")] TgtUnused = 0,
    [pbr::OriginalName("TGT_RESET")] TgtReset = 1,
    [pbr::OriginalName("TGT_START")] TgtStart = 2,
    [pbr::OriginalName("TGT_STANDARD")] TgtStandard = 3,
    [pbr::OriginalName("TGT_END")] TgtEnd = 4,
  }

  public enum WatchType {
    [pbr::OriginalName("WT_UNUSED")] WtUnused = 0,
    [pbr::OriginalName("WT_COLOR")] WtColor = 1,
    [pbr::OriginalName("WT_IMAGE_STATIC")] WtImageStatic = 2,
    [pbr::OriginalName("WT_CHARACTER_SET")] WtCharacterSet = 3,
  }

  public enum CharacterJustify {
    [pbr::OriginalName("CHARACTER_JUSTIFY_UNUSED")] Unused = 0,
    [pbr::OriginalName("CHARACTER_JUSTIFY_LEFT")] Left = 1,
    [pbr::OriginalName("CHARACTER_JUSTIFY_RIGHT")] Right = 2,
  }

  public enum CharacterZOrder {
    [pbr::OriginalName("CHARACTER_Z_UNUSED")] CharacterZUnused = 0,
    [pbr::OriginalName("CHARACTER_Z_LEFT_TO_RIGHT")] CharacterZLeftToRight = 1,
    [pbr::OriginalName("CHARACTER_Z_RIGHT_TO_LEFT")] CharacterZRightToLeft = 2,
  }

  #endregion

  #region Messages
  public sealed partial class UScalar2d : pb::IMessage<UScalar2d> {
    private static readonly pb::MessageParser<UScalar2d> _parser = new pb::MessageParser<UScalar2d>(() => new UScalar2d());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<UScalar2d> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::LiveSplit.Lazysplits.Proto.LzsCvDataProtoCsReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UScalar2d() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UScalar2d(UScalar2d other) : this() {
      x_ = other.x_;
      y_ = other.y_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UScalar2d Clone() {
      return new UScalar2d(this);
    }

    /// <summary>Field number for the "x" field.</summary>
    public const int XFieldNumber = 1;
    private uint x_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint X {
      get { return x_; }
      set {
        x_ = value;
      }
    }

    /// <summary>Field number for the "y" field.</summary>
    public const int YFieldNumber = 2;
    private uint y_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint Y {
      get { return y_; }
      set {
        y_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as UScalar2d);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(UScalar2d other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (X != other.X) return false;
      if (Y != other.Y) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (X != 0) hash ^= X.GetHashCode();
      if (Y != 0) hash ^= Y.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (X != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(X);
      }
      if (Y != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(Y);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (X != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(X);
      }
      if (Y != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Y);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(UScalar2d other) {
      if (other == null) {
        return;
      }
      if (other.X != 0) {
        X = other.X;
      }
      if (other.Y != 0) {
        Y = other.Y;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            X = input.ReadUInt32();
            break;
          }
          case 16: {
            Y = input.ReadUInt32();
            break;
          }
        }
      }
    }

  }

  public sealed partial class RGBColor : pb::IMessage<RGBColor> {
    private static readonly pb::MessageParser<RGBColor> _parser = new pb::MessageParser<RGBColor>(() => new RGBColor());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<RGBColor> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::LiveSplit.Lazysplits.Proto.LzsCvDataProtoCsReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RGBColor() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RGBColor(RGBColor other) : this() {
      r_ = other.r_;
      g_ = other.g_;
      b_ = other.b_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RGBColor Clone() {
      return new RGBColor(this);
    }

    /// <summary>Field number for the "R" field.</summary>
    public const int RFieldNumber = 1;
    private uint r_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint R {
      get { return r_; }
      set {
        r_ = value;
      }
    }

    /// <summary>Field number for the "G" field.</summary>
    public const int GFieldNumber = 2;
    private uint g_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint G {
      get { return g_; }
      set {
        g_ = value;
      }
    }

    /// <summary>Field number for the "B" field.</summary>
    public const int BFieldNumber = 3;
    private uint b_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint B {
      get { return b_; }
      set {
        b_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as RGBColor);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(RGBColor other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (R != other.R) return false;
      if (G != other.G) return false;
      if (B != other.B) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (R != 0) hash ^= R.GetHashCode();
      if (G != 0) hash ^= G.GetHashCode();
      if (B != 0) hash ^= B.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (R != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(R);
      }
      if (G != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(G);
      }
      if (B != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(B);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (R != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(R);
      }
      if (G != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(G);
      }
      if (B != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(B);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(RGBColor other) {
      if (other == null) {
        return;
      }
      if (other.R != 0) {
        R = other.R;
      }
      if (other.G != 0) {
        G = other.G;
      }
      if (other.B != 0) {
        B = other.B;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            R = input.ReadUInt32();
            break;
          }
          case 16: {
            G = input.ReadUInt32();
            break;
          }
          case 24: {
            B = input.ReadUInt32();
            break;
          }
        }
      }
    }

  }

  public sealed partial class GameList : pb::IMessage<GameList> {
    private static readonly pb::MessageParser<GameList> _parser = new pb::MessageParser<GameList>(() => new GameList());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<GameList> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::LiveSplit.Lazysplits.Proto.LzsCvDataProtoCsReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GameList() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GameList(GameList other) : this() {
      games_ = other.games_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GameList Clone() {
      return new GameList(this);
    }

    /// <summary>Field number for the "games" field.</summary>
    public const int GamesFieldNumber = 1;
    private static readonly pb::FieldCodec<global::LiveSplit.Lazysplits.Proto.GameList.Types.GameEntry> _repeated_games_codec
        = pb::FieldCodec.ForMessage(10, global::LiveSplit.Lazysplits.Proto.GameList.Types.GameEntry.Parser);
    private readonly pbc::RepeatedField<global::LiveSplit.Lazysplits.Proto.GameList.Types.GameEntry> games_ = new pbc::RepeatedField<global::LiveSplit.Lazysplits.Proto.GameList.Types.GameEntry>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::LiveSplit.Lazysplits.Proto.GameList.Types.GameEntry> Games {
      get { return games_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as GameList);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(GameList other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!games_.Equals(other.games_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= games_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      games_.WriteTo(output, _repeated_games_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += games_.CalculateSize(_repeated_games_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(GameList other) {
      if (other == null) {
        return;
      }
      games_.Add(other.games_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            games_.AddEntriesFrom(input, _repeated_games_codec);
            break;
          }
        }
      }
    }

    #region Nested types
    /// <summary>Container for nested types declared in the GameList message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static partial class Types {
      public sealed partial class GameEntry : pb::IMessage<GameEntry> {
        private static readonly pb::MessageParser<GameEntry> _parser = new pb::MessageParser<GameEntry>(() => new GameEntry());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pb::MessageParser<GameEntry> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::LiveSplit.Lazysplits.Proto.GameList.Descriptor.NestedTypes[0]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public GameEntry() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public GameEntry(GameEntry other) : this() {
          name_ = other.name_;
          relativePath_ = other.relativePath_;
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public GameEntry Clone() {
          return new GameEntry(this);
        }

        /// <summary>Field number for the "name" field.</summary>
        public const int NameFieldNumber = 1;
        private string name_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public string Name {
          get { return name_; }
          set {
            name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        /// <summary>Field number for the "relative_path" field.</summary>
        public const int RelativePathFieldNumber = 2;
        private string relativePath_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public string RelativePath {
          get { return relativePath_; }
          set {
            relativePath_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override bool Equals(object other) {
          return Equals(other as GameEntry);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public bool Equals(GameEntry other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (Name != other.Name) return false;
          if (RelativePath != other.RelativePath) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override int GetHashCode() {
          int hash = 1;
          if (Name.Length != 0) hash ^= Name.GetHashCode();
          if (RelativePath.Length != 0) hash ^= RelativePath.GetHashCode();
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void WriteTo(pb::CodedOutputStream output) {
          if (Name.Length != 0) {
            output.WriteRawTag(10);
            output.WriteString(Name);
          }
          if (RelativePath.Length != 0) {
            output.WriteRawTag(18);
            output.WriteString(RelativePath);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public int CalculateSize() {
          int size = 0;
          if (Name.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
          }
          if (RelativePath.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(RelativePath);
          }
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(GameEntry other) {
          if (other == null) {
            return;
          }
          if (other.Name.Length != 0) {
            Name = other.Name;
          }
          if (other.RelativePath.Length != 0) {
            RelativePath = other.RelativePath;
          }
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(pb::CodedInputStream input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 10: {
                Name = input.ReadString();
                break;
              }
              case 18: {
                RelativePath = input.ReadString();
                break;
              }
            }
          }
        }

      }

    }
    #endregion

  }

  public sealed partial class GameInfo : pb::IMessage<GameInfo> {
    private static readonly pb::MessageParser<GameInfo> _parser = new pb::MessageParser<GameInfo>(() => new GameInfo());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<GameInfo> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::LiveSplit.Lazysplits.Proto.LzsCvDataProtoCsReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GameInfo() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GameInfo(GameInfo other) : this() {
      name_ = other.name_;
      targets_ = other.targets_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GameInfo Clone() {
      return new GameInfo(this);
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 1;
    private string name_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "targets" field.</summary>
    public const int TargetsFieldNumber = 2;
    private static readonly pb::FieldCodec<global::LiveSplit.Lazysplits.Proto.GameInfo.Types.TargetEntry> _repeated_targets_codec
        = pb::FieldCodec.ForMessage(18, global::LiveSplit.Lazysplits.Proto.GameInfo.Types.TargetEntry.Parser);
    private readonly pbc::RepeatedField<global::LiveSplit.Lazysplits.Proto.GameInfo.Types.TargetEntry> targets_ = new pbc::RepeatedField<global::LiveSplit.Lazysplits.Proto.GameInfo.Types.TargetEntry>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::LiveSplit.Lazysplits.Proto.GameInfo.Types.TargetEntry> Targets {
      get { return targets_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as GameInfo);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(GameInfo other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Name != other.Name) return false;
      if(!targets_.Equals(other.targets_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      hash ^= targets_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Name.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Name);
      }
      targets_.WriteTo(output, _repeated_targets_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      size += targets_.CalculateSize(_repeated_targets_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(GameInfo other) {
      if (other == null) {
        return;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      targets_.Add(other.targets_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Name = input.ReadString();
            break;
          }
          case 18: {
            targets_.AddEntriesFrom(input, _repeated_targets_codec);
            break;
          }
        }
      }
    }

    #region Nested types
    /// <summary>Container for nested types declared in the GameInfo message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static partial class Types {
      public sealed partial class TargetEntry : pb::IMessage<TargetEntry> {
        private static readonly pb::MessageParser<TargetEntry> _parser = new pb::MessageParser<TargetEntry>(() => new TargetEntry());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pb::MessageParser<TargetEntry> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::LiveSplit.Lazysplits.Proto.GameInfo.Descriptor.NestedTypes[0]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public TargetEntry() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public TargetEntry(TargetEntry other) : this() {
          name_ = other.name_;
          relativePath_ = other.relativePath_;
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public TargetEntry Clone() {
          return new TargetEntry(this);
        }

        /// <summary>Field number for the "name" field.</summary>
        public const int NameFieldNumber = 1;
        private string name_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public string Name {
          get { return name_; }
          set {
            name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        /// <summary>Field number for the "relative_path" field.</summary>
        public const int RelativePathFieldNumber = 2;
        private string relativePath_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public string RelativePath {
          get { return relativePath_; }
          set {
            relativePath_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override bool Equals(object other) {
          return Equals(other as TargetEntry);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public bool Equals(TargetEntry other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (Name != other.Name) return false;
          if (RelativePath != other.RelativePath) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override int GetHashCode() {
          int hash = 1;
          if (Name.Length != 0) hash ^= Name.GetHashCode();
          if (RelativePath.Length != 0) hash ^= RelativePath.GetHashCode();
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void WriteTo(pb::CodedOutputStream output) {
          if (Name.Length != 0) {
            output.WriteRawTag(10);
            output.WriteString(Name);
          }
          if (RelativePath.Length != 0) {
            output.WriteRawTag(18);
            output.WriteString(RelativePath);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public int CalculateSize() {
          int size = 0;
          if (Name.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
          }
          if (RelativePath.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(RelativePath);
          }
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(TargetEntry other) {
          if (other == null) {
            return;
          }
          if (other.Name.Length != 0) {
            Name = other.Name;
          }
          if (other.RelativePath.Length != 0) {
            RelativePath = other.RelativePath;
          }
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(pb::CodedInputStream input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 10: {
                Name = input.ReadString();
                break;
              }
              case 18: {
                RelativePath = input.ReadString();
                break;
              }
            }
          }
        }

      }

    }
    #endregion

  }

  public sealed partial class TargetInfo : pb::IMessage<TargetInfo> {
    private static readonly pb::MessageParser<TargetInfo> _parser = new pb::MessageParser<TargetInfo>(() => new TargetInfo());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<TargetInfo> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::LiveSplit.Lazysplits.Proto.LzsCvDataProtoCsReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public TargetInfo() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public TargetInfo(TargetInfo other) : this() {
      name_ = other.name_;
      type_ = other.type_;
      splitOffsetMs_ = other.splitOffsetMs_;
      watches_ = other.watches_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public TargetInfo Clone() {
      return new TargetInfo(this);
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 1;
    private string name_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "type" field.</summary>
    public const int TypeFieldNumber = 2;
    private global::LiveSplit.Lazysplits.Proto.TargetType type_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::LiveSplit.Lazysplits.Proto.TargetType Type {
      get { return type_; }
      set {
        type_ = value;
      }
    }

    /// <summary>Field number for the "split_offset_ms" field.</summary>
    public const int SplitOffsetMsFieldNumber = 3;
    private int splitOffsetMs_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int SplitOffsetMs {
      get { return splitOffsetMs_; }
      set {
        splitOffsetMs_ = value;
      }
    }

    /// <summary>Field number for the "watches" field.</summary>
    public const int WatchesFieldNumber = 4;
    private static readonly pb::FieldCodec<global::LiveSplit.Lazysplits.Proto.TargetInfo.Types.WatchEntry> _repeated_watches_codec
        = pb::FieldCodec.ForMessage(34, global::LiveSplit.Lazysplits.Proto.TargetInfo.Types.WatchEntry.Parser);
    private readonly pbc::RepeatedField<global::LiveSplit.Lazysplits.Proto.TargetInfo.Types.WatchEntry> watches_ = new pbc::RepeatedField<global::LiveSplit.Lazysplits.Proto.TargetInfo.Types.WatchEntry>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::LiveSplit.Lazysplits.Proto.TargetInfo.Types.WatchEntry> Watches {
      get { return watches_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as TargetInfo);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(TargetInfo other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Name != other.Name) return false;
      if (Type != other.Type) return false;
      if (SplitOffsetMs != other.SplitOffsetMs) return false;
      if(!watches_.Equals(other.watches_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (Type != 0) hash ^= Type.GetHashCode();
      if (SplitOffsetMs != 0) hash ^= SplitOffsetMs.GetHashCode();
      hash ^= watches_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Name.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Name);
      }
      if (Type != 0) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Type);
      }
      if (SplitOffsetMs != 0) {
        output.WriteRawTag(24);
        output.WriteSInt32(SplitOffsetMs);
      }
      watches_.WriteTo(output, _repeated_watches_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (Type != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
      }
      if (SplitOffsetMs != 0) {
        size += 1 + pb::CodedOutputStream.ComputeSInt32Size(SplitOffsetMs);
      }
      size += watches_.CalculateSize(_repeated_watches_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(TargetInfo other) {
      if (other == null) {
        return;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.Type != 0) {
        Type = other.Type;
      }
      if (other.SplitOffsetMs != 0) {
        SplitOffsetMs = other.SplitOffsetMs;
      }
      watches_.Add(other.watches_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Name = input.ReadString();
            break;
          }
          case 16: {
            type_ = (global::LiveSplit.Lazysplits.Proto.TargetType) input.ReadEnum();
            break;
          }
          case 24: {
            SplitOffsetMs = input.ReadSInt32();
            break;
          }
          case 34: {
            watches_.AddEntriesFrom(input, _repeated_watches_codec);
            break;
          }
        }
      }
    }

    #region Nested types
    /// <summary>Container for nested types declared in the TargetInfo message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static partial class Types {
      public sealed partial class WatchEntry : pb::IMessage<WatchEntry> {
        private static readonly pb::MessageParser<WatchEntry> _parser = new pb::MessageParser<WatchEntry>(() => new WatchEntry());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pb::MessageParser<WatchEntry> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::LiveSplit.Lazysplits.Proto.TargetInfo.Descriptor.NestedTypes[0]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public WatchEntry() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public WatchEntry(WatchEntry other) : this() {
          name_ = other.name_;
          relativePath_ = other.relativePath_;
          index_ = other.index_;
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public WatchEntry Clone() {
          return new WatchEntry(this);
        }

        /// <summary>Field number for the "name" field.</summary>
        public const int NameFieldNumber = 1;
        private string name_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public string Name {
          get { return name_; }
          set {
            name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        /// <summary>Field number for the "relative_path" field.</summary>
        public const int RelativePathFieldNumber = 2;
        private string relativePath_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public string RelativePath {
          get { return relativePath_; }
          set {
            relativePath_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        /// <summary>Field number for the "index" field.</summary>
        public const int IndexFieldNumber = 3;
        private uint index_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public uint Index {
          get { return index_; }
          set {
            index_ = value;
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override bool Equals(object other) {
          return Equals(other as WatchEntry);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public bool Equals(WatchEntry other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (Name != other.Name) return false;
          if (RelativePath != other.RelativePath) return false;
          if (Index != other.Index) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override int GetHashCode() {
          int hash = 1;
          if (Name.Length != 0) hash ^= Name.GetHashCode();
          if (RelativePath.Length != 0) hash ^= RelativePath.GetHashCode();
          if (Index != 0) hash ^= Index.GetHashCode();
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void WriteTo(pb::CodedOutputStream output) {
          if (Name.Length != 0) {
            output.WriteRawTag(10);
            output.WriteString(Name);
          }
          if (RelativePath.Length != 0) {
            output.WriteRawTag(18);
            output.WriteString(RelativePath);
          }
          if (Index != 0) {
            output.WriteRawTag(24);
            output.WriteUInt32(Index);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public int CalculateSize() {
          int size = 0;
          if (Name.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
          }
          if (RelativePath.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(RelativePath);
          }
          if (Index != 0) {
            size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Index);
          }
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(WatchEntry other) {
          if (other == null) {
            return;
          }
          if (other.Name.Length != 0) {
            Name = other.Name;
          }
          if (other.RelativePath.Length != 0) {
            RelativePath = other.RelativePath;
          }
          if (other.Index != 0) {
            Index = other.Index;
          }
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(pb::CodedInputStream input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 10: {
                Name = input.ReadString();
                break;
              }
              case 18: {
                RelativePath = input.ReadString();
                break;
              }
              case 24: {
                Index = input.ReadUInt32();
                break;
              }
            }
          }
        }

      }

    }
    #endregion

  }

  public sealed partial class WatchInfo : pb::IMessage<WatchInfo> {
    private static readonly pb::MessageParser<WatchInfo> _parser = new pb::MessageParser<WatchInfo>(() => new WatchInfo());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<WatchInfo> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::LiveSplit.Lazysplits.Proto.LzsCvDataProtoCsReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public WatchInfo() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public WatchInfo(WatchInfo other) : this() {
      name_ = other.name_;
      type_ = other.type_;
      BaseDimensions = other.baseDimensions_ != null ? other.BaseDimensions.Clone() : null;
      Area = other.area_ != null ? other.Area.Clone() : null;
      Color = other.color_ != null ? other.Color.Clone() : null;
      imgRelativePath_ = other.imgRelativePath_;
      characterJustify_ = other.characterJustify_;
      characterZOrder_ = other.characterZOrder_;
      characters_ = other.characters_.Clone();
      additionalPadding_ = other.additionalPadding_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public WatchInfo Clone() {
      return new WatchInfo(this);
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 1;
    private string name_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "type" field.</summary>
    public const int TypeFieldNumber = 2;
    private global::LiveSplit.Lazysplits.Proto.WatchType type_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::LiveSplit.Lazysplits.Proto.WatchType Type {
      get { return type_; }
      set {
        type_ = value;
      }
    }

    /// <summary>Field number for the "base_dimensions" field.</summary>
    public const int BaseDimensionsFieldNumber = 3;
    private global::LiveSplit.Lazysplits.Proto.UScalar2d baseDimensions_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::LiveSplit.Lazysplits.Proto.UScalar2d BaseDimensions {
      get { return baseDimensions_; }
      set {
        baseDimensions_ = value;
      }
    }

    /// <summary>Field number for the "area" field.</summary>
    public const int AreaFieldNumber = 4;
    private global::LiveSplit.Lazysplits.Proto.WatchInfo.Types.WatchArea area_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::LiveSplit.Lazysplits.Proto.WatchInfo.Types.WatchArea Area {
      get { return area_; }
      set {
        area_ = value;
      }
    }

    /// <summary>Field number for the "color" field.</summary>
    public const int ColorFieldNumber = 5;
    private global::LiveSplit.Lazysplits.Proto.RGBColor color_;
    /// <summary>
    ///color watch specific
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::LiveSplit.Lazysplits.Proto.RGBColor Color {
      get { return color_; }
      set {
        color_ = value;
      }
    }

    /// <summary>Field number for the "img_relative_path" field.</summary>
    public const int ImgRelativePathFieldNumber = 6;
    private string imgRelativePath_ = "";
    /// <summary>
    ///static image/character set specific
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string ImgRelativePath {
      get { return imgRelativePath_; }
      set {
        imgRelativePath_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "character_justify" field.</summary>
    public const int CharacterJustifyFieldNumber = 7;
    private global::LiveSplit.Lazysplits.Proto.CharacterJustify characterJustify_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::LiveSplit.Lazysplits.Proto.CharacterJustify CharacterJustify {
      get { return characterJustify_; }
      set {
        characterJustify_ = value;
      }
    }

    /// <summary>Field number for the "character_z_order" field.</summary>
    public const int CharacterZOrderFieldNumber = 8;
    private global::LiveSplit.Lazysplits.Proto.CharacterZOrder characterZOrder_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::LiveSplit.Lazysplits.Proto.CharacterZOrder CharacterZOrder {
      get { return characterZOrder_; }
      set {
        characterZOrder_ = value;
      }
    }

    /// <summary>Field number for the "characters" field.</summary>
    public const int CharactersFieldNumber = 9;
    private static readonly pb::FieldCodec<global::LiveSplit.Lazysplits.Proto.WatchInfo.Types.CharacterEntry> _repeated_characters_codec
        = pb::FieldCodec.ForMessage(74, global::LiveSplit.Lazysplits.Proto.WatchInfo.Types.CharacterEntry.Parser);
    private readonly pbc::RepeatedField<global::LiveSplit.Lazysplits.Proto.WatchInfo.Types.CharacterEntry> characters_ = new pbc::RepeatedField<global::LiveSplit.Lazysplits.Proto.WatchInfo.Types.CharacterEntry>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::LiveSplit.Lazysplits.Proto.WatchInfo.Types.CharacterEntry> Characters {
      get { return characters_; }
    }

    /// <summary>Field number for the "additional_padding" field.</summary>
    public const int AdditionalPaddingFieldNumber = 10;
    private static readonly pb::FieldCodec<global::LiveSplit.Lazysplits.Proto.WatchInfo.Types.AdditionalPaddingEntry> _repeated_additionalPadding_codec
        = pb::FieldCodec.ForMessage(82, global::LiveSplit.Lazysplits.Proto.WatchInfo.Types.AdditionalPaddingEntry.Parser);
    private readonly pbc::RepeatedField<global::LiveSplit.Lazysplits.Proto.WatchInfo.Types.AdditionalPaddingEntry> additionalPadding_ = new pbc::RepeatedField<global::LiveSplit.Lazysplits.Proto.WatchInfo.Types.AdditionalPaddingEntry>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::LiveSplit.Lazysplits.Proto.WatchInfo.Types.AdditionalPaddingEntry> AdditionalPadding {
      get { return additionalPadding_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as WatchInfo);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(WatchInfo other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Name != other.Name) return false;
      if (Type != other.Type) return false;
      if (!object.Equals(BaseDimensions, other.BaseDimensions)) return false;
      if (!object.Equals(Area, other.Area)) return false;
      if (!object.Equals(Color, other.Color)) return false;
      if (ImgRelativePath != other.ImgRelativePath) return false;
      if (CharacterJustify != other.CharacterJustify) return false;
      if (CharacterZOrder != other.CharacterZOrder) return false;
      if(!characters_.Equals(other.characters_)) return false;
      if(!additionalPadding_.Equals(other.additionalPadding_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (Type != 0) hash ^= Type.GetHashCode();
      if (baseDimensions_ != null) hash ^= BaseDimensions.GetHashCode();
      if (area_ != null) hash ^= Area.GetHashCode();
      if (color_ != null) hash ^= Color.GetHashCode();
      if (ImgRelativePath.Length != 0) hash ^= ImgRelativePath.GetHashCode();
      if (CharacterJustify != 0) hash ^= CharacterJustify.GetHashCode();
      if (CharacterZOrder != 0) hash ^= CharacterZOrder.GetHashCode();
      hash ^= characters_.GetHashCode();
      hash ^= additionalPadding_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Name.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Name);
      }
      if (Type != 0) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Type);
      }
      if (baseDimensions_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(BaseDimensions);
      }
      if (area_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(Area);
      }
      if (color_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(Color);
      }
      if (ImgRelativePath.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(ImgRelativePath);
      }
      if (CharacterJustify != 0) {
        output.WriteRawTag(56);
        output.WriteEnum((int) CharacterJustify);
      }
      if (CharacterZOrder != 0) {
        output.WriteRawTag(64);
        output.WriteEnum((int) CharacterZOrder);
      }
      characters_.WriteTo(output, _repeated_characters_codec);
      additionalPadding_.WriteTo(output, _repeated_additionalPadding_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (Type != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
      }
      if (baseDimensions_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(BaseDimensions);
      }
      if (area_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Area);
      }
      if (color_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Color);
      }
      if (ImgRelativePath.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ImgRelativePath);
      }
      if (CharacterJustify != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) CharacterJustify);
      }
      if (CharacterZOrder != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) CharacterZOrder);
      }
      size += characters_.CalculateSize(_repeated_characters_codec);
      size += additionalPadding_.CalculateSize(_repeated_additionalPadding_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(WatchInfo other) {
      if (other == null) {
        return;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.Type != 0) {
        Type = other.Type;
      }
      if (other.baseDimensions_ != null) {
        if (baseDimensions_ == null) {
          baseDimensions_ = new global::LiveSplit.Lazysplits.Proto.UScalar2d();
        }
        BaseDimensions.MergeFrom(other.BaseDimensions);
      }
      if (other.area_ != null) {
        if (area_ == null) {
          area_ = new global::LiveSplit.Lazysplits.Proto.WatchInfo.Types.WatchArea();
        }
        Area.MergeFrom(other.Area);
      }
      if (other.color_ != null) {
        if (color_ == null) {
          color_ = new global::LiveSplit.Lazysplits.Proto.RGBColor();
        }
        Color.MergeFrom(other.Color);
      }
      if (other.ImgRelativePath.Length != 0) {
        ImgRelativePath = other.ImgRelativePath;
      }
      if (other.CharacterJustify != 0) {
        CharacterJustify = other.CharacterJustify;
      }
      if (other.CharacterZOrder != 0) {
        CharacterZOrder = other.CharacterZOrder;
      }
      characters_.Add(other.characters_);
      additionalPadding_.Add(other.additionalPadding_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Name = input.ReadString();
            break;
          }
          case 16: {
            type_ = (global::LiveSplit.Lazysplits.Proto.WatchType) input.ReadEnum();
            break;
          }
          case 26: {
            if (baseDimensions_ == null) {
              baseDimensions_ = new global::LiveSplit.Lazysplits.Proto.UScalar2d();
            }
            input.ReadMessage(baseDimensions_);
            break;
          }
          case 34: {
            if (area_ == null) {
              area_ = new global::LiveSplit.Lazysplits.Proto.WatchInfo.Types.WatchArea();
            }
            input.ReadMessage(area_);
            break;
          }
          case 42: {
            if (color_ == null) {
              color_ = new global::LiveSplit.Lazysplits.Proto.RGBColor();
            }
            input.ReadMessage(color_);
            break;
          }
          case 50: {
            ImgRelativePath = input.ReadString();
            break;
          }
          case 56: {
            characterJustify_ = (global::LiveSplit.Lazysplits.Proto.CharacterJustify) input.ReadEnum();
            break;
          }
          case 64: {
            characterZOrder_ = (global::LiveSplit.Lazysplits.Proto.CharacterZOrder) input.ReadEnum();
            break;
          }
          case 74: {
            characters_.AddEntriesFrom(input, _repeated_characters_codec);
            break;
          }
          case 82: {
            additionalPadding_.AddEntriesFrom(input, _repeated_additionalPadding_codec);
            break;
          }
        }
      }
    }

    #region Nested types
    /// <summary>Container for nested types declared in the WatchInfo message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static partial class Types {
      public sealed partial class WatchArea : pb::IMessage<WatchArea> {
        private static readonly pb::MessageParser<WatchArea> _parser = new pb::MessageParser<WatchArea>(() => new WatchArea());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pb::MessageParser<WatchArea> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::LiveSplit.Lazysplits.Proto.WatchInfo.Descriptor.NestedTypes[0]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public WatchArea() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public WatchArea(WatchArea other) : this() {
          Loc = other.loc_ != null ? other.Loc.Clone() : null;
          Size = other.size_ != null ? other.Size.Clone() : null;
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public WatchArea Clone() {
          return new WatchArea(this);
        }

        /// <summary>Field number for the "loc" field.</summary>
        public const int LocFieldNumber = 1;
        private global::LiveSplit.Lazysplits.Proto.UScalar2d loc_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public global::LiveSplit.Lazysplits.Proto.UScalar2d Loc {
          get { return loc_; }
          set {
            loc_ = value;
          }
        }

        /// <summary>Field number for the "size" field.</summary>
        public const int SizeFieldNumber = 2;
        private global::LiveSplit.Lazysplits.Proto.UScalar2d size_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public global::LiveSplit.Lazysplits.Proto.UScalar2d Size {
          get { return size_; }
          set {
            size_ = value;
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override bool Equals(object other) {
          return Equals(other as WatchArea);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public bool Equals(WatchArea other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (!object.Equals(Loc, other.Loc)) return false;
          if (!object.Equals(Size, other.Size)) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override int GetHashCode() {
          int hash = 1;
          if (loc_ != null) hash ^= Loc.GetHashCode();
          if (size_ != null) hash ^= Size.GetHashCode();
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void WriteTo(pb::CodedOutputStream output) {
          if (loc_ != null) {
            output.WriteRawTag(10);
            output.WriteMessage(Loc);
          }
          if (size_ != null) {
            output.WriteRawTag(18);
            output.WriteMessage(Size);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public int CalculateSize() {
          int size = 0;
          if (loc_ != null) {
            size += 1 + pb::CodedOutputStream.ComputeMessageSize(Loc);
          }
          if (size_ != null) {
            size += 1 + pb::CodedOutputStream.ComputeMessageSize(Size);
          }
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(WatchArea other) {
          if (other == null) {
            return;
          }
          if (other.loc_ != null) {
            if (loc_ == null) {
              loc_ = new global::LiveSplit.Lazysplits.Proto.UScalar2d();
            }
            Loc.MergeFrom(other.Loc);
          }
          if (other.size_ != null) {
            if (size_ == null) {
              size_ = new global::LiveSplit.Lazysplits.Proto.UScalar2d();
            }
            Size.MergeFrom(other.Size);
          }
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(pb::CodedInputStream input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 10: {
                if (loc_ == null) {
                  loc_ = new global::LiveSplit.Lazysplits.Proto.UScalar2d();
                }
                input.ReadMessage(loc_);
                break;
              }
              case 18: {
                if (size_ == null) {
                  size_ = new global::LiveSplit.Lazysplits.Proto.UScalar2d();
                }
                input.ReadMessage(size_);
                break;
              }
            }
          }
        }

      }

      /// <summary>
      ///character set specific
      /// </summary>
      public sealed partial class CharacterEntry : pb::IMessage<CharacterEntry> {
        private static readonly pb::MessageParser<CharacterEntry> _parser = new pb::MessageParser<CharacterEntry>(() => new CharacterEntry());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pb::MessageParser<CharacterEntry> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::LiveSplit.Lazysplits.Proto.WatchInfo.Descriptor.NestedTypes[1]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public CharacterEntry() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public CharacterEntry(CharacterEntry other) : this() {
          characterIndex_ = other.characterIndex_;
          characterVal_ = other.characterVal_;
          xPadding_ = other.xPadding_;
          yPadding_ = other.yPadding_;
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public CharacterEntry Clone() {
          return new CharacterEntry(this);
        }

        /// <summary>Field number for the "character_index" field.</summary>
        public const int CharacterIndexFieldNumber = 1;
        private uint characterIndex_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public uint CharacterIndex {
          get { return characterIndex_; }
          set {
            characterIndex_ = value;
          }
        }

        /// <summary>Field number for the "character_val" field.</summary>
        public const int CharacterValFieldNumber = 2;
        private string characterVal_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public string CharacterVal {
          get { return characterVal_; }
          set {
            characterVal_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        /// <summary>Field number for the "x_padding" field.</summary>
        public const int XPaddingFieldNumber = 3;
        private int xPadding_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public int XPadding {
          get { return xPadding_; }
          set {
            xPadding_ = value;
          }
        }

        /// <summary>Field number for the "y_padding" field.</summary>
        public const int YPaddingFieldNumber = 4;
        private int yPadding_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public int YPadding {
          get { return yPadding_; }
          set {
            yPadding_ = value;
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override bool Equals(object other) {
          return Equals(other as CharacterEntry);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public bool Equals(CharacterEntry other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (CharacterIndex != other.CharacterIndex) return false;
          if (CharacterVal != other.CharacterVal) return false;
          if (XPadding != other.XPadding) return false;
          if (YPadding != other.YPadding) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override int GetHashCode() {
          int hash = 1;
          if (CharacterIndex != 0) hash ^= CharacterIndex.GetHashCode();
          if (CharacterVal.Length != 0) hash ^= CharacterVal.GetHashCode();
          if (XPadding != 0) hash ^= XPadding.GetHashCode();
          if (YPadding != 0) hash ^= YPadding.GetHashCode();
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void WriteTo(pb::CodedOutputStream output) {
          if (CharacterIndex != 0) {
            output.WriteRawTag(8);
            output.WriteUInt32(CharacterIndex);
          }
          if (CharacterVal.Length != 0) {
            output.WriteRawTag(18);
            output.WriteString(CharacterVal);
          }
          if (XPadding != 0) {
            output.WriteRawTag(24);
            output.WriteSInt32(XPadding);
          }
          if (YPadding != 0) {
            output.WriteRawTag(32);
            output.WriteSInt32(YPadding);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public int CalculateSize() {
          int size = 0;
          if (CharacterIndex != 0) {
            size += 1 + pb::CodedOutputStream.ComputeUInt32Size(CharacterIndex);
          }
          if (CharacterVal.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(CharacterVal);
          }
          if (XPadding != 0) {
            size += 1 + pb::CodedOutputStream.ComputeSInt32Size(XPadding);
          }
          if (YPadding != 0) {
            size += 1 + pb::CodedOutputStream.ComputeSInt32Size(YPadding);
          }
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(CharacterEntry other) {
          if (other == null) {
            return;
          }
          if (other.CharacterIndex != 0) {
            CharacterIndex = other.CharacterIndex;
          }
          if (other.CharacterVal.Length != 0) {
            CharacterVal = other.CharacterVal;
          }
          if (other.XPadding != 0) {
            XPadding = other.XPadding;
          }
          if (other.YPadding != 0) {
            YPadding = other.YPadding;
          }
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(pb::CodedInputStream input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 8: {
                CharacterIndex = input.ReadUInt32();
                break;
              }
              case 18: {
                CharacterVal = input.ReadString();
                break;
              }
              case 24: {
                XPadding = input.ReadSInt32();
                break;
              }
              case 32: {
                YPadding = input.ReadSInt32();
                break;
              }
            }
          }
        }

      }

      public sealed partial class AdditionalPaddingEntry : pb::IMessage<AdditionalPaddingEntry> {
        private static readonly pb::MessageParser<AdditionalPaddingEntry> _parser = new pb::MessageParser<AdditionalPaddingEntry>(() => new AdditionalPaddingEntry());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pb::MessageParser<AdditionalPaddingEntry> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::LiveSplit.Lazysplits.Proto.WatchInfo.Descriptor.NestedTypes[2]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public AdditionalPaddingEntry() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public AdditionalPaddingEntry(AdditionalPaddingEntry other) : this() {
          characterLengthThreshold_ = other.characterLengthThreshold_;
          padding_ = other.padding_;
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public AdditionalPaddingEntry Clone() {
          return new AdditionalPaddingEntry(this);
        }

        /// <summary>Field number for the "character_length_threshold" field.</summary>
        public const int CharacterLengthThresholdFieldNumber = 1;
        private uint characterLengthThreshold_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public uint CharacterLengthThreshold {
          get { return characterLengthThreshold_; }
          set {
            characterLengthThreshold_ = value;
          }
        }

        /// <summary>Field number for the "padding" field.</summary>
        public const int PaddingFieldNumber = 2;
        private int padding_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public int Padding {
          get { return padding_; }
          set {
            padding_ = value;
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override bool Equals(object other) {
          return Equals(other as AdditionalPaddingEntry);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public bool Equals(AdditionalPaddingEntry other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (CharacterLengthThreshold != other.CharacterLengthThreshold) return false;
          if (Padding != other.Padding) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override int GetHashCode() {
          int hash = 1;
          if (CharacterLengthThreshold != 0) hash ^= CharacterLengthThreshold.GetHashCode();
          if (Padding != 0) hash ^= Padding.GetHashCode();
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void WriteTo(pb::CodedOutputStream output) {
          if (CharacterLengthThreshold != 0) {
            output.WriteRawTag(8);
            output.WriteUInt32(CharacterLengthThreshold);
          }
          if (Padding != 0) {
            output.WriteRawTag(16);
            output.WriteSInt32(Padding);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public int CalculateSize() {
          int size = 0;
          if (CharacterLengthThreshold != 0) {
            size += 1 + pb::CodedOutputStream.ComputeUInt32Size(CharacterLengthThreshold);
          }
          if (Padding != 0) {
            size += 1 + pb::CodedOutputStream.ComputeSInt32Size(Padding);
          }
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(AdditionalPaddingEntry other) {
          if (other == null) {
            return;
          }
          if (other.CharacterLengthThreshold != 0) {
            CharacterLengthThreshold = other.CharacterLengthThreshold;
          }
          if (other.Padding != 0) {
            Padding = other.Padding;
          }
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(pb::CodedInputStream input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 8: {
                CharacterLengthThreshold = input.ReadUInt32();
                break;
              }
              case 16: {
                Padding = input.ReadSInt32();
                break;
              }
            }
          }
        }

      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
