// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CsMessage.proto

#ifndef PROTOBUF_CsMessage_2eproto__INCLUDED
#define PROTOBUF_CsMessage_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3003000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3003000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
namespace LiveSplit {
namespace Lazysplits {
namespace Proto {
class CsMessage;
class CsMessageDefaultTypeInternal;
extern CsMessageDefaultTypeInternal _CsMessage_default_instance_;
}  // namespace Proto
}  // namespace Lazysplits
}  // namespace LiveSplit

namespace LiveSplit {
namespace Lazysplits {
namespace Proto {

namespace protobuf_CsMessage_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[];
  static const ::google::protobuf::uint32 offsets[];
  static void InitDefaultsImpl();
  static void Shutdown();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_CsMessage_2eproto

enum CsMessage_MessageType {
  CsMessage_MessageType_NONE = 0,
  CsMessage_MessageType_PIPE_INFO = 1,
  CsMessage_MessageType_SOURCE_CV_TARGET = 2,
  CsMessage_MessageType_CsMessage_MessageType_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  CsMessage_MessageType_CsMessage_MessageType_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool CsMessage_MessageType_IsValid(int value);
const CsMessage_MessageType CsMessage_MessageType_MessageType_MIN = CsMessage_MessageType_NONE;
const CsMessage_MessageType CsMessage_MessageType_MessageType_MAX = CsMessage_MessageType_SOURCE_CV_TARGET;
const int CsMessage_MessageType_MessageType_ARRAYSIZE = CsMessage_MessageType_MessageType_MAX + 1;

const ::google::protobuf::EnumDescriptor* CsMessage_MessageType_descriptor();
inline const ::std::string& CsMessage_MessageType_Name(CsMessage_MessageType value) {
  return ::google::protobuf::internal::NameOfEnum(
    CsMessage_MessageType_descriptor(), value);
}
inline bool CsMessage_MessageType_Parse(
    const ::std::string& name, CsMessage_MessageType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<CsMessage_MessageType>(
    CsMessage_MessageType_descriptor(), name, value);
}
// ===================================================================

class CsMessage : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:LiveSplit.Lazysplits.Proto.CsMessage) */ {
 public:
  CsMessage();
  virtual ~CsMessage();

  CsMessage(const CsMessage& from);

  inline CsMessage& operator=(const CsMessage& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const CsMessage& default_instance();

  static inline const CsMessage* internal_default_instance() {
    return reinterpret_cast<const CsMessage*>(
               &_CsMessage_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(CsMessage* other);

  // implements Message ----------------------------------------------

  inline CsMessage* New() const PROTOBUF_FINAL { return New(NULL); }

  CsMessage* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const CsMessage& from);
  void MergeFrom(const CsMessage& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(CsMessage* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  typedef CsMessage_MessageType MessageType;
  static const MessageType NONE =
    CsMessage_MessageType_NONE;
  static const MessageType PIPE_INFO =
    CsMessage_MessageType_PIPE_INFO;
  static const MessageType SOURCE_CV_TARGET =
    CsMessage_MessageType_SOURCE_CV_TARGET;
  static inline bool MessageType_IsValid(int value) {
    return CsMessage_MessageType_IsValid(value);
  }
  static const MessageType MessageType_MIN =
    CsMessage_MessageType_MessageType_MIN;
  static const MessageType MessageType_MAX =
    CsMessage_MessageType_MessageType_MAX;
  static const int MessageType_ARRAYSIZE =
    CsMessage_MessageType_MessageType_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  MessageType_descriptor() {
    return CsMessage_MessageType_descriptor();
  }
  static inline const ::std::string& MessageType_Name(MessageType value) {
    return CsMessage_MessageType_Name(value);
  }
  static inline bool MessageType_Parse(const ::std::string& name,
      MessageType* value) {
    return CsMessage_MessageType_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // int32 message_id = 1;
  void clear_message_id();
  static const int kMessageIdFieldNumber = 1;
  ::google::protobuf::int32 message_id() const;
  void set_message_id(::google::protobuf::int32 value);

  // .LiveSplit.Lazysplits.Proto.CsMessage.MessageType message_type = 2;
  void clear_message_type();
  static const int kMessageTypeFieldNumber = 2;
  ::LiveSplit::Lazysplits::Proto::CsMessage_MessageType message_type() const;
  void set_message_type(::LiveSplit::Lazysplits::Proto::CsMessage_MessageType value);

  // bool pipe_connected = 3;
  void clear_pipe_connected();
  static const int kPipeConnectedFieldNumber = 3;
  bool pipe_connected() const;
  void set_pipe_connected(bool value);

  // uint32 target_index = 4;
  void clear_target_index();
  static const int kTargetIndexFieldNumber = 4;
  ::google::protobuf::uint32 target_index() const;
  void set_target_index(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:LiveSplit.Lazysplits.Proto.CsMessage)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::int32 message_id_;
  int message_type_;
  bool pipe_connected_;
  ::google::protobuf::uint32 target_index_;
  mutable int _cached_size_;
  friend struct protobuf_CsMessage_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// CsMessage

// int32 message_id = 1;
inline void CsMessage::clear_message_id() {
  message_id_ = 0;
}
inline ::google::protobuf::int32 CsMessage::message_id() const {
  // @@protoc_insertion_point(field_get:LiveSplit.Lazysplits.Proto.CsMessage.message_id)
  return message_id_;
}
inline void CsMessage::set_message_id(::google::protobuf::int32 value) {
  
  message_id_ = value;
  // @@protoc_insertion_point(field_set:LiveSplit.Lazysplits.Proto.CsMessage.message_id)
}

// .LiveSplit.Lazysplits.Proto.CsMessage.MessageType message_type = 2;
inline void CsMessage::clear_message_type() {
  message_type_ = 0;
}
inline ::LiveSplit::Lazysplits::Proto::CsMessage_MessageType CsMessage::message_type() const {
  // @@protoc_insertion_point(field_get:LiveSplit.Lazysplits.Proto.CsMessage.message_type)
  return static_cast< ::LiveSplit::Lazysplits::Proto::CsMessage_MessageType >(message_type_);
}
inline void CsMessage::set_message_type(::LiveSplit::Lazysplits::Proto::CsMessage_MessageType value) {
  
  message_type_ = value;
  // @@protoc_insertion_point(field_set:LiveSplit.Lazysplits.Proto.CsMessage.message_type)
}

// bool pipe_connected = 3;
inline void CsMessage::clear_pipe_connected() {
  pipe_connected_ = false;
}
inline bool CsMessage::pipe_connected() const {
  // @@protoc_insertion_point(field_get:LiveSplit.Lazysplits.Proto.CsMessage.pipe_connected)
  return pipe_connected_;
}
inline void CsMessage::set_pipe_connected(bool value) {
  
  pipe_connected_ = value;
  // @@protoc_insertion_point(field_set:LiveSplit.Lazysplits.Proto.CsMessage.pipe_connected)
}

// uint32 target_index = 4;
inline void CsMessage::clear_target_index() {
  target_index_ = 0u;
}
inline ::google::protobuf::uint32 CsMessage::target_index() const {
  // @@protoc_insertion_point(field_get:LiveSplit.Lazysplits.Proto.CsMessage.target_index)
  return target_index_;
}
inline void CsMessage::set_target_index(::google::protobuf::uint32 value) {
  
  target_index_ = value;
  // @@protoc_insertion_point(field_set:LiveSplit.Lazysplits.Proto.CsMessage.target_index)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)


}  // namespace Proto
}  // namespace Lazysplits
}  // namespace LiveSplit

#ifndef SWIG
namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::LiveSplit::Lazysplits::Proto::CsMessage_MessageType> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::LiveSplit::Lazysplits::Proto::CsMessage_MessageType>() {
  return ::LiveSplit::Lazysplits::Proto::CsMessage_MessageType_descriptor();
}

}  // namespace protobuf
}  // namespace google
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_CsMessage_2eproto__INCLUDED
