// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CsMessage.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "CsMessage.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace LiveSplit {
namespace Lazysplits {
namespace Proto {
class CsMessageDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<CsMessage> {
} _CsMessage_default_instance_;

namespace protobuf_CsMessage_2eproto {


namespace {

::google::protobuf::Metadata file_level_metadata[1];
const ::google::protobuf::EnumDescriptor* file_level_enum_descriptors[1];

}  // namespace

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTableField
    const TableStruct::entries[] = {
  {0, 0, 0, ::google::protobuf::internal::kInvalidMask, 0, 0},
};

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::AuxillaryParseTableField
    const TableStruct::aux[] = {
  ::google::protobuf::internal::AuxillaryParseTableField(),
};
PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTable const
    TableStruct::schema[] = {
  { NULL, NULL, 0, -1, -1, false },
};

const ::google::protobuf::uint32 TableStruct::offsets[] = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CsMessage, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CsMessage, message_id_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CsMessage, message_type_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CsMessage, pipe_connected_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CsMessage, target_index_),
};

static const ::google::protobuf::internal::MigrationSchema schemas[] = {
  { 0, -1, sizeof(CsMessage)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&_CsMessage_default_instance_),
};

namespace {

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "CsMessage.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, file_level_enum_descriptors, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 1);
}

}  // namespace

void TableStruct::Shutdown() {
  _CsMessage_default_instance_.Shutdown();
  delete file_level_metadata[0].reflection;
}

void TableStruct::InitDefaultsImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::internal::InitProtobufDefaults();
  _CsMessage_default_instance_.DefaultConstruct();
}

void InitDefaults() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &TableStruct::InitDefaultsImpl);
}
void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] = {
      "\n\017CsMessage.proto\022\032LiveSplit.Lazysplits."
      "Proto\"\324\001\n\tCsMessage\022\022\n\nmessage_id\030\001 \001(\005\022"
      "G\n\014message_type\030\002 \001(\01621.LiveSplit.Lazysp"
      "lits.Proto.CsMessage.MessageType\022\026\n\016pipe"
      "_connected\030\003 \001(\010\022\024\n\014target_index\030\004 \001(\r\"<"
      "\n\013MessageType\022\010\n\004NONE\020\000\022\r\n\tPIPE_INFO\020\001\022\024"
      "\n\020SOURCE_CV_TARGET\020\002b\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 268);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "CsMessage.proto", &protobuf_RegisterTypes);
  ::google::protobuf::internal::OnShutdown(&TableStruct::Shutdown);
}

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;

}  // namespace protobuf_CsMessage_2eproto

const ::google::protobuf::EnumDescriptor* CsMessage_MessageType_descriptor() {
  protobuf_CsMessage_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_CsMessage_2eproto::file_level_enum_descriptors[0];
}
bool CsMessage_MessageType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const CsMessage_MessageType CsMessage::NONE;
const CsMessage_MessageType CsMessage::PIPE_INFO;
const CsMessage_MessageType CsMessage::SOURCE_CV_TARGET;
const CsMessage_MessageType CsMessage::MessageType_MIN;
const CsMessage_MessageType CsMessage::MessageType_MAX;
const int CsMessage::MessageType_ARRAYSIZE;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int CsMessage::kMessageIdFieldNumber;
const int CsMessage::kMessageTypeFieldNumber;
const int CsMessage::kPipeConnectedFieldNumber;
const int CsMessage::kTargetIndexFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

CsMessage::CsMessage()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_CsMessage_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:LiveSplit.Lazysplits.Proto.CsMessage)
}
CsMessage::CsMessage(const CsMessage& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&message_id_, &from.message_id_,
    reinterpret_cast<char*>(&target_index_) -
    reinterpret_cast<char*>(&message_id_) + sizeof(target_index_));
  // @@protoc_insertion_point(copy_constructor:LiveSplit.Lazysplits.Proto.CsMessage)
}

void CsMessage::SharedCtor() {
  ::memset(&message_id_, 0, reinterpret_cast<char*>(&target_index_) -
    reinterpret_cast<char*>(&message_id_) + sizeof(target_index_));
  _cached_size_ = 0;
}

CsMessage::~CsMessage() {
  // @@protoc_insertion_point(destructor:LiveSplit.Lazysplits.Proto.CsMessage)
  SharedDtor();
}

void CsMessage::SharedDtor() {
}

void CsMessage::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* CsMessage::descriptor() {
  protobuf_CsMessage_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_CsMessage_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const CsMessage& CsMessage::default_instance() {
  protobuf_CsMessage_2eproto::InitDefaults();
  return *internal_default_instance();
}

CsMessage* CsMessage::New(::google::protobuf::Arena* arena) const {
  CsMessage* n = new CsMessage;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void CsMessage::Clear() {
// @@protoc_insertion_point(message_clear_start:LiveSplit.Lazysplits.Proto.CsMessage)
  ::memset(&message_id_, 0, reinterpret_cast<char*>(&target_index_) -
    reinterpret_cast<char*>(&message_id_) + sizeof(target_index_));
}

bool CsMessage::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:LiveSplit.Lazysplits.Proto.CsMessage)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int32 message_id = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &message_id_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .LiveSplit.Lazysplits.Proto.CsMessage.MessageType message_type = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u)) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_message_type(static_cast< ::LiveSplit::Lazysplits::Proto::CsMessage_MessageType >(value));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // bool pipe_connected = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(24u)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &pipe_connected_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint32 target_index = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(32u)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &target_index_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:LiveSplit.Lazysplits.Proto.CsMessage)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:LiveSplit.Lazysplits.Proto.CsMessage)
  return false;
#undef DO_
}

void CsMessage::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:LiveSplit.Lazysplits.Proto.CsMessage)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 message_id = 1;
  if (this->message_id() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->message_id(), output);
  }

  // .LiveSplit.Lazysplits.Proto.CsMessage.MessageType message_type = 2;
  if (this->message_type() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      2, this->message_type(), output);
  }

  // bool pipe_connected = 3;
  if (this->pipe_connected() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(3, this->pipe_connected(), output);
  }

  // uint32 target_index = 4;
  if (this->target_index() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(4, this->target_index(), output);
  }

  // @@protoc_insertion_point(serialize_end:LiveSplit.Lazysplits.Proto.CsMessage)
}

::google::protobuf::uint8* CsMessage::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:LiveSplit.Lazysplits.Proto.CsMessage)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 message_id = 1;
  if (this->message_id() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->message_id(), target);
  }

  // .LiveSplit.Lazysplits.Proto.CsMessage.MessageType message_type = 2;
  if (this->message_type() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      2, this->message_type(), target);
  }

  // bool pipe_connected = 3;
  if (this->pipe_connected() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(3, this->pipe_connected(), target);
  }

  // uint32 target_index = 4;
  if (this->target_index() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(4, this->target_index(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:LiveSplit.Lazysplits.Proto.CsMessage)
  return target;
}

size_t CsMessage::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:LiveSplit.Lazysplits.Proto.CsMessage)
  size_t total_size = 0;

  // int32 message_id = 1;
  if (this->message_id() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->message_id());
  }

  // .LiveSplit.Lazysplits.Proto.CsMessage.MessageType message_type = 2;
  if (this->message_type() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->message_type());
  }

  // bool pipe_connected = 3;
  if (this->pipe_connected() != 0) {
    total_size += 1 + 1;
  }

  // uint32 target_index = 4;
  if (this->target_index() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->target_index());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void CsMessage::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:LiveSplit.Lazysplits.Proto.CsMessage)
  GOOGLE_DCHECK_NE(&from, this);
  const CsMessage* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const CsMessage>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:LiveSplit.Lazysplits.Proto.CsMessage)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:LiveSplit.Lazysplits.Proto.CsMessage)
    MergeFrom(*source);
  }
}

void CsMessage::MergeFrom(const CsMessage& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:LiveSplit.Lazysplits.Proto.CsMessage)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.message_id() != 0) {
    set_message_id(from.message_id());
  }
  if (from.message_type() != 0) {
    set_message_type(from.message_type());
  }
  if (from.pipe_connected() != 0) {
    set_pipe_connected(from.pipe_connected());
  }
  if (from.target_index() != 0) {
    set_target_index(from.target_index());
  }
}

void CsMessage::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:LiveSplit.Lazysplits.Proto.CsMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void CsMessage::CopyFrom(const CsMessage& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:LiveSplit.Lazysplits.Proto.CsMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CsMessage::IsInitialized() const {
  return true;
}

void CsMessage::Swap(CsMessage* other) {
  if (other == this) return;
  InternalSwap(other);
}
void CsMessage::InternalSwap(CsMessage* other) {
  std::swap(message_id_, other->message_id_);
  std::swap(message_type_, other->message_type_);
  std::swap(pipe_connected_, other->pipe_connected_);
  std::swap(target_index_, other->target_index_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata CsMessage::GetMetadata() const {
  protobuf_CsMessage_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_CsMessage_2eproto::file_level_metadata[kIndexInFileMessages];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// CsMessage

// int32 message_id = 1;
void CsMessage::clear_message_id() {
  message_id_ = 0;
}
::google::protobuf::int32 CsMessage::message_id() const {
  // @@protoc_insertion_point(field_get:LiveSplit.Lazysplits.Proto.CsMessage.message_id)
  return message_id_;
}
void CsMessage::set_message_id(::google::protobuf::int32 value) {
  
  message_id_ = value;
  // @@protoc_insertion_point(field_set:LiveSplit.Lazysplits.Proto.CsMessage.message_id)
}

// .LiveSplit.Lazysplits.Proto.CsMessage.MessageType message_type = 2;
void CsMessage::clear_message_type() {
  message_type_ = 0;
}
::LiveSplit::Lazysplits::Proto::CsMessage_MessageType CsMessage::message_type() const {
  // @@protoc_insertion_point(field_get:LiveSplit.Lazysplits.Proto.CsMessage.message_type)
  return static_cast< ::LiveSplit::Lazysplits::Proto::CsMessage_MessageType >(message_type_);
}
void CsMessage::set_message_type(::LiveSplit::Lazysplits::Proto::CsMessage_MessageType value) {
  
  message_type_ = value;
  // @@protoc_insertion_point(field_set:LiveSplit.Lazysplits.Proto.CsMessage.message_type)
}

// bool pipe_connected = 3;
void CsMessage::clear_pipe_connected() {
  pipe_connected_ = false;
}
bool CsMessage::pipe_connected() const {
  // @@protoc_insertion_point(field_get:LiveSplit.Lazysplits.Proto.CsMessage.pipe_connected)
  return pipe_connected_;
}
void CsMessage::set_pipe_connected(bool value) {
  
  pipe_connected_ = value;
  // @@protoc_insertion_point(field_set:LiveSplit.Lazysplits.Proto.CsMessage.pipe_connected)
}

// uint32 target_index = 4;
void CsMessage::clear_target_index() {
  target_index_ = 0u;
}
::google::protobuf::uint32 CsMessage::target_index() const {
  // @@protoc_insertion_point(field_get:LiveSplit.Lazysplits.Proto.CsMessage.target_index)
  return target_index_;
}
void CsMessage::set_target_index(::google::protobuf::uint32 value) {
  
  target_index_ = value;
  // @@protoc_insertion_point(field_set:LiveSplit.Lazysplits.Proto.CsMessage.target_index)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace Proto
}  // namespace Lazysplits
}  // namespace LiveSplit

// @@protoc_insertion_point(global_scope)
