// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LzsPipeProtoCpp.proto

#include "LzsPipeProtoCpp.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace Lazysplits {
namespace Proto {
class CppMessageDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<CppMessage>
      _instance;
} _CppMessage_default_instance_;
class CsMessageDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<CsMessage>
      _instance;
} _CsMessage_default_instance_;
}  // namespace Proto
}  // namespace Lazysplits
namespace protobuf_LzsPipeProtoCpp_2eproto {
static void InitDefaultsCppMessage() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::Lazysplits::Proto::_CppMessage_default_instance_;
    new (ptr) ::Lazysplits::Proto::CppMessage();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::Lazysplits::Proto::CppMessage::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_CppMessage =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsCppMessage}, {}};

static void InitDefaultsCsMessage() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::Lazysplits::Proto::_CsMessage_default_instance_;
    new (ptr) ::Lazysplits::Proto::CsMessage();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::Lazysplits::Proto::CsMessage::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_CsMessage =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsCsMessage}, {}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_CppMessage.base);
  ::google::protobuf::internal::InitSCC(&scc_info_CsMessage.base);
}

::google::protobuf::Metadata file_level_metadata[2];
const ::google::protobuf::EnumDescriptor* file_level_enum_descriptors[2];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::Lazysplits::Proto::CppMessage, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::Lazysplits::Proto::CppMessage, message_id_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::Lazysplits::Proto::CppMessage, message_type_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::Lazysplits::Proto::CppMessage, pipe_connected_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::Lazysplits::Proto::CppMessage, target_index_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::Lazysplits::Proto::CppMessage, target_timestamp_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::Lazysplits::Proto::CsMessage, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::Lazysplits::Proto::CsMessage, message_id_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::Lazysplits::Proto::CsMessage, message_type_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::Lazysplits::Proto::CsMessage, pipe_connected_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::Lazysplits::Proto::CsMessage, target_index_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::Lazysplits::Proto::CppMessage)},
  { 10, -1, sizeof(::Lazysplits::Proto::CsMessage)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::Lazysplits::Proto::_CppMessage_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::Lazysplits::Proto::_CsMessage_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "LzsPipeProtoCpp.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, file_level_enum_descriptors, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 2);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\025LzsPipeProtoCpp.proto\022\020Lazysplits.Prot"
      "o\"\371\001\n\nCppMessage\022\022\n\nmessage_id\030\001 \001(\005\022>\n\014"
      "message_type\030\002 \001(\0162(.Lazysplits.Proto.Cp"
      "pMessage.MessageType\022\026\n\016pipe_connected\030\003"
      " \001(\010\022\024\n\014target_index\030\004 \001(\r\022\030\n\020target_tim"
      "estamp\030\005 \001(\004\"O\n\013MessageType\022\010\n\004NONE\020\000\022\r\n"
      "\tPIPE_INFO\020\001\022\025\n\021REQUEST_CV_TARGET\020\002\022\020\n\014T"
      "ARGET_FOUND\020\003\"\312\001\n\tCsMessage\022\022\n\nmessage_i"
      "d\030\001 \001(\005\022=\n\014message_type\030\002 \001(\0162\'.Lazyspli"
      "ts.Proto.CsMessage.MessageType\022\026\n\016pipe_c"
      "onnected\030\003 \001(\010\022\024\n\014target_index\030\004 \001(\r\"<\n\013"
      "MessageType\022\010\n\004NONE\020\000\022\r\n\tPIPE_INFO\020\001\022\024\n\020"
      "SOURCE_CV_TARGET\020\002b\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 506);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "LzsPipeProtoCpp.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_LzsPipeProtoCpp_2eproto
namespace Lazysplits {
namespace Proto {
const ::google::protobuf::EnumDescriptor* CppMessage_MessageType_descriptor() {
  protobuf_LzsPipeProtoCpp_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_LzsPipeProtoCpp_2eproto::file_level_enum_descriptors[0];
}
bool CppMessage_MessageType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
      return true;
    default:
      return false;
  }
}

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const CppMessage_MessageType CppMessage::NONE;
const CppMessage_MessageType CppMessage::PIPE_INFO;
const CppMessage_MessageType CppMessage::REQUEST_CV_TARGET;
const CppMessage_MessageType CppMessage::TARGET_FOUND;
const CppMessage_MessageType CppMessage::MessageType_MIN;
const CppMessage_MessageType CppMessage::MessageType_MAX;
const int CppMessage::MessageType_ARRAYSIZE;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900
const ::google::protobuf::EnumDescriptor* CsMessage_MessageType_descriptor() {
  protobuf_LzsPipeProtoCpp_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_LzsPipeProtoCpp_2eproto::file_level_enum_descriptors[1];
}
bool CsMessage_MessageType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const CsMessage_MessageType CsMessage::NONE;
const CsMessage_MessageType CsMessage::PIPE_INFO;
const CsMessage_MessageType CsMessage::SOURCE_CV_TARGET;
const CsMessage_MessageType CsMessage::MessageType_MIN;
const CsMessage_MessageType CsMessage::MessageType_MAX;
const int CsMessage::MessageType_ARRAYSIZE;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

// ===================================================================

void CppMessage::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int CppMessage::kMessageIdFieldNumber;
const int CppMessage::kMessageTypeFieldNumber;
const int CppMessage::kPipeConnectedFieldNumber;
const int CppMessage::kTargetIndexFieldNumber;
const int CppMessage::kTargetTimestampFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

CppMessage::CppMessage()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_LzsPipeProtoCpp_2eproto::scc_info_CppMessage.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:Lazysplits.Proto.CppMessage)
}
CppMessage::CppMessage(const CppMessage& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&message_id_, &from.message_id_,
    static_cast<size_t>(reinterpret_cast<char*>(&target_timestamp_) -
    reinterpret_cast<char*>(&message_id_)) + sizeof(target_timestamp_));
  // @@protoc_insertion_point(copy_constructor:Lazysplits.Proto.CppMessage)
}

void CppMessage::SharedCtor() {
  ::memset(&message_id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&target_timestamp_) -
      reinterpret_cast<char*>(&message_id_)) + sizeof(target_timestamp_));
}

CppMessage::~CppMessage() {
  // @@protoc_insertion_point(destructor:Lazysplits.Proto.CppMessage)
  SharedDtor();
}

void CppMessage::SharedDtor() {
}

void CppMessage::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* CppMessage::descriptor() {
  ::protobuf_LzsPipeProtoCpp_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_LzsPipeProtoCpp_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const CppMessage& CppMessage::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_LzsPipeProtoCpp_2eproto::scc_info_CppMessage.base);
  return *internal_default_instance();
}


void CppMessage::Clear() {
// @@protoc_insertion_point(message_clear_start:Lazysplits.Proto.CppMessage)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&message_id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&target_timestamp_) -
      reinterpret_cast<char*>(&message_id_)) + sizeof(target_timestamp_));
  _internal_metadata_.Clear();
}

bool CppMessage::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:Lazysplits.Proto.CppMessage)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int32 message_id = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &message_id_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .Lazysplits.Proto.CppMessage.MessageType message_type = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u /* 16 & 0xFF */)) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_message_type(static_cast< ::Lazysplits::Proto::CppMessage_MessageType >(value));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // bool pipe_connected = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(24u /* 24 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &pipe_connected_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint32 target_index = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(32u /* 32 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &target_index_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint64 target_timestamp = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(40u /* 40 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &target_timestamp_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:Lazysplits.Proto.CppMessage)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:Lazysplits.Proto.CppMessage)
  return false;
#undef DO_
}

void CppMessage::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:Lazysplits.Proto.CppMessage)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 message_id = 1;
  if (this->message_id() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->message_id(), output);
  }

  // .Lazysplits.Proto.CppMessage.MessageType message_type = 2;
  if (this->message_type() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      2, this->message_type(), output);
  }

  // bool pipe_connected = 3;
  if (this->pipe_connected() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(3, this->pipe_connected(), output);
  }

  // uint32 target_index = 4;
  if (this->target_index() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(4, this->target_index(), output);
  }

  // uint64 target_timestamp = 5;
  if (this->target_timestamp() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(5, this->target_timestamp(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:Lazysplits.Proto.CppMessage)
}

::google::protobuf::uint8* CppMessage::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:Lazysplits.Proto.CppMessage)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 message_id = 1;
  if (this->message_id() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->message_id(), target);
  }

  // .Lazysplits.Proto.CppMessage.MessageType message_type = 2;
  if (this->message_type() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      2, this->message_type(), target);
  }

  // bool pipe_connected = 3;
  if (this->pipe_connected() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(3, this->pipe_connected(), target);
  }

  // uint32 target_index = 4;
  if (this->target_index() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(4, this->target_index(), target);
  }

  // uint64 target_timestamp = 5;
  if (this->target_timestamp() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt64ToArray(5, this->target_timestamp(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Lazysplits.Proto.CppMessage)
  return target;
}

size_t CppMessage::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Lazysplits.Proto.CppMessage)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // int32 message_id = 1;
  if (this->message_id() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->message_id());
  }

  // .Lazysplits.Proto.CppMessage.MessageType message_type = 2;
  if (this->message_type() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->message_type());
  }

  // bool pipe_connected = 3;
  if (this->pipe_connected() != 0) {
    total_size += 1 + 1;
  }

  // uint32 target_index = 4;
  if (this->target_index() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->target_index());
  }

  // uint64 target_timestamp = 5;
  if (this->target_timestamp() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt64Size(
        this->target_timestamp());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void CppMessage::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:Lazysplits.Proto.CppMessage)
  GOOGLE_DCHECK_NE(&from, this);
  const CppMessage* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const CppMessage>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:Lazysplits.Proto.CppMessage)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:Lazysplits.Proto.CppMessage)
    MergeFrom(*source);
  }
}

void CppMessage::MergeFrom(const CppMessage& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:Lazysplits.Proto.CppMessage)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.message_id() != 0) {
    set_message_id(from.message_id());
  }
  if (from.message_type() != 0) {
    set_message_type(from.message_type());
  }
  if (from.pipe_connected() != 0) {
    set_pipe_connected(from.pipe_connected());
  }
  if (from.target_index() != 0) {
    set_target_index(from.target_index());
  }
  if (from.target_timestamp() != 0) {
    set_target_timestamp(from.target_timestamp());
  }
}

void CppMessage::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:Lazysplits.Proto.CppMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void CppMessage::CopyFrom(const CppMessage& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Lazysplits.Proto.CppMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CppMessage::IsInitialized() const {
  return true;
}

void CppMessage::Swap(CppMessage* other) {
  if (other == this) return;
  InternalSwap(other);
}
void CppMessage::InternalSwap(CppMessage* other) {
  using std::swap;
  swap(message_id_, other->message_id_);
  swap(message_type_, other->message_type_);
  swap(pipe_connected_, other->pipe_connected_);
  swap(target_index_, other->target_index_);
  swap(target_timestamp_, other->target_timestamp_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata CppMessage::GetMetadata() const {
  protobuf_LzsPipeProtoCpp_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_LzsPipeProtoCpp_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void CsMessage::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int CsMessage::kMessageIdFieldNumber;
const int CsMessage::kMessageTypeFieldNumber;
const int CsMessage::kPipeConnectedFieldNumber;
const int CsMessage::kTargetIndexFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

CsMessage::CsMessage()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_LzsPipeProtoCpp_2eproto::scc_info_CsMessage.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:Lazysplits.Proto.CsMessage)
}
CsMessage::CsMessage(const CsMessage& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&message_id_, &from.message_id_,
    static_cast<size_t>(reinterpret_cast<char*>(&target_index_) -
    reinterpret_cast<char*>(&message_id_)) + sizeof(target_index_));
  // @@protoc_insertion_point(copy_constructor:Lazysplits.Proto.CsMessage)
}

void CsMessage::SharedCtor() {
  ::memset(&message_id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&target_index_) -
      reinterpret_cast<char*>(&message_id_)) + sizeof(target_index_));
}

CsMessage::~CsMessage() {
  // @@protoc_insertion_point(destructor:Lazysplits.Proto.CsMessage)
  SharedDtor();
}

void CsMessage::SharedDtor() {
}

void CsMessage::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* CsMessage::descriptor() {
  ::protobuf_LzsPipeProtoCpp_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_LzsPipeProtoCpp_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const CsMessage& CsMessage::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_LzsPipeProtoCpp_2eproto::scc_info_CsMessage.base);
  return *internal_default_instance();
}


void CsMessage::Clear() {
// @@protoc_insertion_point(message_clear_start:Lazysplits.Proto.CsMessage)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&message_id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&target_index_) -
      reinterpret_cast<char*>(&message_id_)) + sizeof(target_index_));
  _internal_metadata_.Clear();
}

bool CsMessage::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:Lazysplits.Proto.CsMessage)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int32 message_id = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &message_id_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .Lazysplits.Proto.CsMessage.MessageType message_type = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u /* 16 & 0xFF */)) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_message_type(static_cast< ::Lazysplits::Proto::CsMessage_MessageType >(value));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // bool pipe_connected = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(24u /* 24 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &pipe_connected_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint32 target_index = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(32u /* 32 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &target_index_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:Lazysplits.Proto.CsMessage)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:Lazysplits.Proto.CsMessage)
  return false;
#undef DO_
}

void CsMessage::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:Lazysplits.Proto.CsMessage)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 message_id = 1;
  if (this->message_id() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->message_id(), output);
  }

  // .Lazysplits.Proto.CsMessage.MessageType message_type = 2;
  if (this->message_type() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      2, this->message_type(), output);
  }

  // bool pipe_connected = 3;
  if (this->pipe_connected() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(3, this->pipe_connected(), output);
  }

  // uint32 target_index = 4;
  if (this->target_index() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(4, this->target_index(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:Lazysplits.Proto.CsMessage)
}

::google::protobuf::uint8* CsMessage::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:Lazysplits.Proto.CsMessage)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 message_id = 1;
  if (this->message_id() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->message_id(), target);
  }

  // .Lazysplits.Proto.CsMessage.MessageType message_type = 2;
  if (this->message_type() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      2, this->message_type(), target);
  }

  // bool pipe_connected = 3;
  if (this->pipe_connected() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(3, this->pipe_connected(), target);
  }

  // uint32 target_index = 4;
  if (this->target_index() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(4, this->target_index(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Lazysplits.Proto.CsMessage)
  return target;
}

size_t CsMessage::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Lazysplits.Proto.CsMessage)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // int32 message_id = 1;
  if (this->message_id() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->message_id());
  }

  // .Lazysplits.Proto.CsMessage.MessageType message_type = 2;
  if (this->message_type() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->message_type());
  }

  // bool pipe_connected = 3;
  if (this->pipe_connected() != 0) {
    total_size += 1 + 1;
  }

  // uint32 target_index = 4;
  if (this->target_index() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->target_index());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void CsMessage::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:Lazysplits.Proto.CsMessage)
  GOOGLE_DCHECK_NE(&from, this);
  const CsMessage* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const CsMessage>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:Lazysplits.Proto.CsMessage)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:Lazysplits.Proto.CsMessage)
    MergeFrom(*source);
  }
}

void CsMessage::MergeFrom(const CsMessage& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:Lazysplits.Proto.CsMessage)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.message_id() != 0) {
    set_message_id(from.message_id());
  }
  if (from.message_type() != 0) {
    set_message_type(from.message_type());
  }
  if (from.pipe_connected() != 0) {
    set_pipe_connected(from.pipe_connected());
  }
  if (from.target_index() != 0) {
    set_target_index(from.target_index());
  }
}

void CsMessage::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:Lazysplits.Proto.CsMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void CsMessage::CopyFrom(const CsMessage& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Lazysplits.Proto.CsMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CsMessage::IsInitialized() const {
  return true;
}

void CsMessage::Swap(CsMessage* other) {
  if (other == this) return;
  InternalSwap(other);
}
void CsMessage::InternalSwap(CsMessage* other) {
  using std::swap;
  swap(message_id_, other->message_id_);
  swap(message_type_, other->message_type_);
  swap(pipe_connected_, other->pipe_connected_);
  swap(target_index_, other->target_index_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata CsMessage::GetMetadata() const {
  protobuf_LzsPipeProtoCpp_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_LzsPipeProtoCpp_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace Proto
}  // namespace Lazysplits
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::Lazysplits::Proto::CppMessage* Arena::CreateMaybeMessage< ::Lazysplits::Proto::CppMessage >(Arena* arena) {
  return Arena::CreateInternal< ::Lazysplits::Proto::CppMessage >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::Lazysplits::Proto::CsMessage* Arena::CreateMaybeMessage< ::Lazysplits::Proto::CsMessage >(Arena* arena) {
  return Arena::CreateInternal< ::Lazysplits::Proto::CsMessage >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
