// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LzsProtobufCpp.proto

#ifndef PROTOBUF_INCLUDED_LzsProtobufCpp_2eproto
#define PROTOBUF_INCLUDED_LzsProtobufCpp_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3005001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_LzsProtobufCpp_2eproto 

namespace protobuf_LzsProtobufCpp_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[2];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_LzsProtobufCpp_2eproto
namespace Lazysplits {
namespace Proto {
class CppMessage;
class CppMessageDefaultTypeInternal;
extern CppMessageDefaultTypeInternal _CppMessage_default_instance_;
class CsMessage;
class CsMessageDefaultTypeInternal;
extern CsMessageDefaultTypeInternal _CsMessage_default_instance_;
}  // namespace Proto
}  // namespace Lazysplits
namespace google {
namespace protobuf {
template<> ::Lazysplits::Proto::CppMessage* Arena::CreateMaybeMessage<::Lazysplits::Proto::CppMessage>(Arena*);
template<> ::Lazysplits::Proto::CsMessage* Arena::CreateMaybeMessage<::Lazysplits::Proto::CsMessage>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace Lazysplits {
namespace Proto {

enum CppMessage_MessageType {
  CppMessage_MessageType_NONE = 0,
  CppMessage_MessageType_PIPE_INFO = 1,
  CppMessage_MessageType_REQUEST_CV_TARGET = 2,
  CppMessage_MessageType_TARGET_FOUND = 3,
  CppMessage_MessageType_CppMessage_MessageType_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  CppMessage_MessageType_CppMessage_MessageType_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool CppMessage_MessageType_IsValid(int value);
const CppMessage_MessageType CppMessage_MessageType_MessageType_MIN = CppMessage_MessageType_NONE;
const CppMessage_MessageType CppMessage_MessageType_MessageType_MAX = CppMessage_MessageType_TARGET_FOUND;
const int CppMessage_MessageType_MessageType_ARRAYSIZE = CppMessage_MessageType_MessageType_MAX + 1;

const ::google::protobuf::EnumDescriptor* CppMessage_MessageType_descriptor();
inline const ::std::string& CppMessage_MessageType_Name(CppMessage_MessageType value) {
  return ::google::protobuf::internal::NameOfEnum(
    CppMessage_MessageType_descriptor(), value);
}
inline bool CppMessage_MessageType_Parse(
    const ::std::string& name, CppMessage_MessageType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<CppMessage_MessageType>(
    CppMessage_MessageType_descriptor(), name, value);
}
enum CsMessage_MessageType {
  CsMessage_MessageType_NONE = 0,
  CsMessage_MessageType_PIPE_INFO = 1,
  CsMessage_MessageType_SOURCE_CV_TARGET = 2,
  CsMessage_MessageType_CsMessage_MessageType_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  CsMessage_MessageType_CsMessage_MessageType_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool CsMessage_MessageType_IsValid(int value);
const CsMessage_MessageType CsMessage_MessageType_MessageType_MIN = CsMessage_MessageType_NONE;
const CsMessage_MessageType CsMessage_MessageType_MessageType_MAX = CsMessage_MessageType_SOURCE_CV_TARGET;
const int CsMessage_MessageType_MessageType_ARRAYSIZE = CsMessage_MessageType_MessageType_MAX + 1;

const ::google::protobuf::EnumDescriptor* CsMessage_MessageType_descriptor();
inline const ::std::string& CsMessage_MessageType_Name(CsMessage_MessageType value) {
  return ::google::protobuf::internal::NameOfEnum(
    CsMessage_MessageType_descriptor(), value);
}
inline bool CsMessage_MessageType_Parse(
    const ::std::string& name, CsMessage_MessageType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<CsMessage_MessageType>(
    CsMessage_MessageType_descriptor(), name, value);
}
// ===================================================================

class CppMessage : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Lazysplits.Proto.CppMessage) */ {
 public:
  CppMessage();
  virtual ~CppMessage();

  CppMessage(const CppMessage& from);

  inline CppMessage& operator=(const CppMessage& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  CppMessage(CppMessage&& from) noexcept
    : CppMessage() {
    *this = ::std::move(from);
  }

  inline CppMessage& operator=(CppMessage&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const CppMessage& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const CppMessage* internal_default_instance() {
    return reinterpret_cast<const CppMessage*>(
               &_CppMessage_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(CppMessage* other);
  friend void swap(CppMessage& a, CppMessage& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline CppMessage* New() const final {
    return CreateMaybeMessage<CppMessage>(NULL);
  }

  CppMessage* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<CppMessage>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const CppMessage& from);
  void MergeFrom(const CppMessage& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(CppMessage* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  typedef CppMessage_MessageType MessageType;
  static const MessageType NONE =
    CppMessage_MessageType_NONE;
  static const MessageType PIPE_INFO =
    CppMessage_MessageType_PIPE_INFO;
  static const MessageType REQUEST_CV_TARGET =
    CppMessage_MessageType_REQUEST_CV_TARGET;
  static const MessageType TARGET_FOUND =
    CppMessage_MessageType_TARGET_FOUND;
  static inline bool MessageType_IsValid(int value) {
    return CppMessage_MessageType_IsValid(value);
  }
  static const MessageType MessageType_MIN =
    CppMessage_MessageType_MessageType_MIN;
  static const MessageType MessageType_MAX =
    CppMessage_MessageType_MessageType_MAX;
  static const int MessageType_ARRAYSIZE =
    CppMessage_MessageType_MessageType_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  MessageType_descriptor() {
    return CppMessage_MessageType_descriptor();
  }
  static inline const ::std::string& MessageType_Name(MessageType value) {
    return CppMessage_MessageType_Name(value);
  }
  static inline bool MessageType_Parse(const ::std::string& name,
      MessageType* value) {
    return CppMessage_MessageType_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // int32 message_id = 1;
  void clear_message_id();
  static const int kMessageIdFieldNumber = 1;
  ::google::protobuf::int32 message_id() const;
  void set_message_id(::google::protobuf::int32 value);

  // .Lazysplits.Proto.CppMessage.MessageType message_type = 2;
  void clear_message_type();
  static const int kMessageTypeFieldNumber = 2;
  ::Lazysplits::Proto::CppMessage_MessageType message_type() const;
  void set_message_type(::Lazysplits::Proto::CppMessage_MessageType value);

  // bool pipe_connected = 3;
  void clear_pipe_connected();
  static const int kPipeConnectedFieldNumber = 3;
  bool pipe_connected() const;
  void set_pipe_connected(bool value);

  // uint32 target_index = 4;
  void clear_target_index();
  static const int kTargetIndexFieldNumber = 4;
  ::google::protobuf::uint32 target_index() const;
  void set_target_index(::google::protobuf::uint32 value);

  // uint64 target_timestamp = 5;
  void clear_target_timestamp();
  static const int kTargetTimestampFieldNumber = 5;
  ::google::protobuf::uint64 target_timestamp() const;
  void set_target_timestamp(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:Lazysplits.Proto.CppMessage)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::int32 message_id_;
  int message_type_;
  bool pipe_connected_;
  ::google::protobuf::uint32 target_index_;
  ::google::protobuf::uint64 target_timestamp_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_LzsProtobufCpp_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class CsMessage : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Lazysplits.Proto.CsMessage) */ {
 public:
  CsMessage();
  virtual ~CsMessage();

  CsMessage(const CsMessage& from);

  inline CsMessage& operator=(const CsMessage& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  CsMessage(CsMessage&& from) noexcept
    : CsMessage() {
    *this = ::std::move(from);
  }

  inline CsMessage& operator=(CsMessage&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const CsMessage& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const CsMessage* internal_default_instance() {
    return reinterpret_cast<const CsMessage*>(
               &_CsMessage_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(CsMessage* other);
  friend void swap(CsMessage& a, CsMessage& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline CsMessage* New() const final {
    return CreateMaybeMessage<CsMessage>(NULL);
  }

  CsMessage* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<CsMessage>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const CsMessage& from);
  void MergeFrom(const CsMessage& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(CsMessage* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  typedef CsMessage_MessageType MessageType;
  static const MessageType NONE =
    CsMessage_MessageType_NONE;
  static const MessageType PIPE_INFO =
    CsMessage_MessageType_PIPE_INFO;
  static const MessageType SOURCE_CV_TARGET =
    CsMessage_MessageType_SOURCE_CV_TARGET;
  static inline bool MessageType_IsValid(int value) {
    return CsMessage_MessageType_IsValid(value);
  }
  static const MessageType MessageType_MIN =
    CsMessage_MessageType_MessageType_MIN;
  static const MessageType MessageType_MAX =
    CsMessage_MessageType_MessageType_MAX;
  static const int MessageType_ARRAYSIZE =
    CsMessage_MessageType_MessageType_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  MessageType_descriptor() {
    return CsMessage_MessageType_descriptor();
  }
  static inline const ::std::string& MessageType_Name(MessageType value) {
    return CsMessage_MessageType_Name(value);
  }
  static inline bool MessageType_Parse(const ::std::string& name,
      MessageType* value) {
    return CsMessage_MessageType_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // int32 message_id = 1;
  void clear_message_id();
  static const int kMessageIdFieldNumber = 1;
  ::google::protobuf::int32 message_id() const;
  void set_message_id(::google::protobuf::int32 value);

  // .Lazysplits.Proto.CsMessage.MessageType message_type = 2;
  void clear_message_type();
  static const int kMessageTypeFieldNumber = 2;
  ::Lazysplits::Proto::CsMessage_MessageType message_type() const;
  void set_message_type(::Lazysplits::Proto::CsMessage_MessageType value);

  // bool pipe_connected = 3;
  void clear_pipe_connected();
  static const int kPipeConnectedFieldNumber = 3;
  bool pipe_connected() const;
  void set_pipe_connected(bool value);

  // uint32 target_index = 4;
  void clear_target_index();
  static const int kTargetIndexFieldNumber = 4;
  ::google::protobuf::uint32 target_index() const;
  void set_target_index(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:Lazysplits.Proto.CsMessage)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::int32 message_id_;
  int message_type_;
  bool pipe_connected_;
  ::google::protobuf::uint32 target_index_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_LzsProtobufCpp_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// CppMessage

// int32 message_id = 1;
inline void CppMessage::clear_message_id() {
  message_id_ = 0;
}
inline ::google::protobuf::int32 CppMessage::message_id() const {
  // @@protoc_insertion_point(field_get:Lazysplits.Proto.CppMessage.message_id)
  return message_id_;
}
inline void CppMessage::set_message_id(::google::protobuf::int32 value) {
  
  message_id_ = value;
  // @@protoc_insertion_point(field_set:Lazysplits.Proto.CppMessage.message_id)
}

// .Lazysplits.Proto.CppMessage.MessageType message_type = 2;
inline void CppMessage::clear_message_type() {
  message_type_ = 0;
}
inline ::Lazysplits::Proto::CppMessage_MessageType CppMessage::message_type() const {
  // @@protoc_insertion_point(field_get:Lazysplits.Proto.CppMessage.message_type)
  return static_cast< ::Lazysplits::Proto::CppMessage_MessageType >(message_type_);
}
inline void CppMessage::set_message_type(::Lazysplits::Proto::CppMessage_MessageType value) {
  
  message_type_ = value;
  // @@protoc_insertion_point(field_set:Lazysplits.Proto.CppMessage.message_type)
}

// bool pipe_connected = 3;
inline void CppMessage::clear_pipe_connected() {
  pipe_connected_ = false;
}
inline bool CppMessage::pipe_connected() const {
  // @@protoc_insertion_point(field_get:Lazysplits.Proto.CppMessage.pipe_connected)
  return pipe_connected_;
}
inline void CppMessage::set_pipe_connected(bool value) {
  
  pipe_connected_ = value;
  // @@protoc_insertion_point(field_set:Lazysplits.Proto.CppMessage.pipe_connected)
}

// uint32 target_index = 4;
inline void CppMessage::clear_target_index() {
  target_index_ = 0u;
}
inline ::google::protobuf::uint32 CppMessage::target_index() const {
  // @@protoc_insertion_point(field_get:Lazysplits.Proto.CppMessage.target_index)
  return target_index_;
}
inline void CppMessage::set_target_index(::google::protobuf::uint32 value) {
  
  target_index_ = value;
  // @@protoc_insertion_point(field_set:Lazysplits.Proto.CppMessage.target_index)
}

// uint64 target_timestamp = 5;
inline void CppMessage::clear_target_timestamp() {
  target_timestamp_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 CppMessage::target_timestamp() const {
  // @@protoc_insertion_point(field_get:Lazysplits.Proto.CppMessage.target_timestamp)
  return target_timestamp_;
}
inline void CppMessage::set_target_timestamp(::google::protobuf::uint64 value) {
  
  target_timestamp_ = value;
  // @@protoc_insertion_point(field_set:Lazysplits.Proto.CppMessage.target_timestamp)
}

// -------------------------------------------------------------------

// CsMessage

// int32 message_id = 1;
inline void CsMessage::clear_message_id() {
  message_id_ = 0;
}
inline ::google::protobuf::int32 CsMessage::message_id() const {
  // @@protoc_insertion_point(field_get:Lazysplits.Proto.CsMessage.message_id)
  return message_id_;
}
inline void CsMessage::set_message_id(::google::protobuf::int32 value) {
  
  message_id_ = value;
  // @@protoc_insertion_point(field_set:Lazysplits.Proto.CsMessage.message_id)
}

// .Lazysplits.Proto.CsMessage.MessageType message_type = 2;
inline void CsMessage::clear_message_type() {
  message_type_ = 0;
}
inline ::Lazysplits::Proto::CsMessage_MessageType CsMessage::message_type() const {
  // @@protoc_insertion_point(field_get:Lazysplits.Proto.CsMessage.message_type)
  return static_cast< ::Lazysplits::Proto::CsMessage_MessageType >(message_type_);
}
inline void CsMessage::set_message_type(::Lazysplits::Proto::CsMessage_MessageType value) {
  
  message_type_ = value;
  // @@protoc_insertion_point(field_set:Lazysplits.Proto.CsMessage.message_type)
}

// bool pipe_connected = 3;
inline void CsMessage::clear_pipe_connected() {
  pipe_connected_ = false;
}
inline bool CsMessage::pipe_connected() const {
  // @@protoc_insertion_point(field_get:Lazysplits.Proto.CsMessage.pipe_connected)
  return pipe_connected_;
}
inline void CsMessage::set_pipe_connected(bool value) {
  
  pipe_connected_ = value;
  // @@protoc_insertion_point(field_set:Lazysplits.Proto.CsMessage.pipe_connected)
}

// uint32 target_index = 4;
inline void CsMessage::clear_target_index() {
  target_index_ = 0u;
}
inline ::google::protobuf::uint32 CsMessage::target_index() const {
  // @@protoc_insertion_point(field_get:Lazysplits.Proto.CsMessage.target_index)
  return target_index_;
}
inline void CsMessage::set_target_index(::google::protobuf::uint32 value) {
  
  target_index_ = value;
  // @@protoc_insertion_point(field_set:Lazysplits.Proto.CsMessage.target_index)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace Proto
}  // namespace Lazysplits

namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::Lazysplits::Proto::CppMessage_MessageType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::Lazysplits::Proto::CppMessage_MessageType>() {
  return ::Lazysplits::Proto::CppMessage_MessageType_descriptor();
}
template <> struct is_proto_enum< ::Lazysplits::Proto::CsMessage_MessageType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::Lazysplits::Proto::CsMessage_MessageType>() {
  return ::Lazysplits::Proto::CsMessage_MessageType_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_LzsProtobufCpp_2eproto
